apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: hb-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: hb-demo/catalog-service:local
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /ready
              port: 8081
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
