apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

commonLabels:
  environment: staging

images:
  - name: hb-demo/frontend-web
    newTag: staging
  - name: hb-demo/api-gateway
    newTag: staging
  - name: hb-demo/catalog-service
    newTag: staging
  - name: hb-demo/cart-service
    newTag: staging
